Gyre = {}

local AnimationList = {
	{ id=0, name="Idle", },
	{ id=1, name="Death", },
	{ id=2, name="Idle", },
	{ id=3, name="Static", },
	{ id=4, name="Fast Walk", },
	{ id=5, name="Run", },
	{ id=6, name="Dead", },
	{ id=7, name="Idle", },
	{ id=8, name="Take Light Hit", },
	{ id=9, name="Take Medium Hit", },
	{ id=10, name="Take Heavy Hit", },
	{ id=11, name="Turning Left", },
	{ id=12, name="Turning Right", },
	{ id=13, name="Backing Up", },
	{ id=14, name="Stunned", },
	{ id=15, name="Static", },
	{ id=16, name="Claw", },
	{ id=17, name="One Hand Hit", },
	{ id=18, name="Two Hand Hit", },
	{ id=19, name="One Hand Hit", },
	{ id=20, name="Block With Hands", },
	{ id=21, name="Punch in air", },
	{ id=26, name="One Hand Attack Stance", },
	{ id=27, name="Two Hand Attack Stance", },
	{ id=28, name="Two Hand Attack Stance Wide", },
	{ id=29, name="Bow Attack Stance", },
	{ id=30, name="Dodge", },
	{ id=31, name="Idle", },
	{ id=32, name="Hand to Hand", },
	{ id=33, name="Hand to Hand", },	
	{ id=36, name="Take Light Hit", },
	{ id=37, name="jump to float in the air", },
	{ id=38, name="float in the air", },
	{ id=39, name="Land on the Ground", },
	{ id=41, name="Swimming", },
	{ id=42, name="Swimming Forward", },
	{ id=43, name="Swimming Left", },
	{ id=44, name="Swimming Right", },
	{ id=45, name="Swimming Back", },
	{ id=46, name="Shoot Bow", },
	{ id=48, name="Gun Attack Stance", },
	{ id=49, name="Shoot Gun", },
	{ id=55, name="Roar", },
	{ id=57, name="Special One Hand Attack", },
	{ id=58, name="Special Two Hand Attack", },
	{ id=60, name="Chat", },
	{ id=61, name="Eat", },
	{ id=62, name="Mine", },
	{ id=63, name="Combine Tradeskill", },
	{ id=64, name="Talk Loud", },
	{ id=65, name="Shrug", },
	{ id=66, name="Bow", },
	{ id=67, name="Wave", },
	{ id=68, name="Cheer", },
	{ id=69, name="Dance", },
	{ id=70, name="Laugh", },
	{ id=71, name="Sleeping", },
	{ id=72, name="Idle", },
	{ id=73, name="Rude", },
	{ id=74, name="Roar", },
	{ id=75, name="Kneel", },
	{ id=76, name="Kiss", },
	{ id=77, name="Cry", },
	{ id=78, name="Chicken", },
	{ id=79, name="Beg", },
	{ id=80, name="Applaud", },
	{ id=81, name="Shout", },
	{ id=82, name="Flex", },
	{ id=83, name="Flirt", },
	{ id=84, name="Point", },
	{ id=87, name="Shield Bash", },
	{ id=88, name="Left Hand Stab", },
	{ id=89, name="Un/-Equip From Back", },
	{ id=90, name="Un/-Equip From Waist", },
	{ id=91, name="Sitting on Mount", },
	{ id=92, name="Idle", },
	{ id=93, name="Idle", },
	{ id=94, name="Idle", },
	{ id=95, name="Kick", },
	{ id=96, name="Sitting Down", },
	{ id=97, name="Sit", },
	{ id=98, name="Getting Up", },
	{ id=99, name="Lay Down", },
	{ id=100, name="Sleeping", },
	{ id=101, name="Get up", },
	{ id=111, name="Toss", }, --
	{ id=113, name="Salute", },
	{ id=114, name="Kneel", },--
	{ id=116, name="Slappin The Knee", },--
	{ id=118, name="KungFu", },--
	{ id=119, name="Crouching Run", },
	{ id=120, name="Crouch", },
	{ id=124, name="Combat Channel Spell", },
	{ id=125, name="Channel Spell", }, -- Don't Shoot!
	{ id=126, name="Spin", },
	{ id=131, name="Death by Drowning", },
	{ id=132, name="Dead in water", },
	{ id=133, name="Chop Wood", },
	{ id=135, name="Swim (Surface)", },
	{ id=136, name="Blacksmithing", },
	{ id=137, name="Stunned", },
	{ id=138, name="Combine Tradeskill", },
	{ id=139, name="Lay Down", },
	{ id=140, name="Kneel", },
	{ id=141, name="Kneeling", },
	{ id=142, name="Static", },
	{ id=143, name="Sprint", },
}